export const recommendPoetry="https://api.apiopen.top/recommendPoetry"
export const authorSearch="https://api.apiopen.top/searchAuthors?name="
export const poetrySearch="https://api.apiopen.top/searchPoetry?name="
export const likeSearch="https://api.apiopen.top/likePoetry?name="
export const site="xiaoxiang.online"