export const recommendPoetry="http://api.apiopen.top/recommendPoetry"
export const authorSearch="http://api.apiopen.top/searchAuthors?name="
export const poetrySearch="http://api.apiopen.top/searchPoetry?name="
export const likeSearch="https://api.apiopen.top/likePoetry?name="
export const site="xiaoxiang.online"